In [1]:
#Zeros,Ones
#arange
#Empty
#Identity
# linespace
# empty
#axis0,axis1
# Sum function with axis
#transpose matrix
# min & max in array ----> argmax,argmin,argsort (with axis also)
#Matrix operation
# np.sqrt,sum,max,min
#finding the data using where

In [29]:
import numpy as np
np.ones(2)

array([1., 1.])

In [30]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [31]:
# Arange
np.arange(4)

array([0, 1, 2, 3])

In [32]:
np.arange(4,10)

array([4, 5, 6, 7, 8, 9])

In [33]:
np.arange(4,10,2)

array([4, 6, 8])

In [34]:
np.arange(4,10,-2)

array([], dtype=int32)

In [35]:
np.arange(10,4)

array([], dtype=int32)

In [36]:
np.arange(10,4,2)

array([], dtype=int32)

In [37]:
np.arange(10,4,-2)

array([10,  8,  6])

In [38]:
#empty----> khalli / blank/null
np.empty(20)

array([8.95802781e-312, 6.27463370e-322, 0.00000000e+000, 0.00000000e+000,
       6.23058367e-307, 5.30276956e+180, 1.02941932e-071, 4.57665177e-071,
       4.05940975e-086, 3.35809009e-143, 6.01433264e+175, 6.93885958e+218,
       5.56218858e+180, 3.94356143e+180, 9.44410068e+164, 1.84740182e-076,
       1.08414673e-042, 2.12896695e-052, 4.96835765e-143, 1.50008929e+248])

In [39]:
np.empty((5,2))

array([[3.16053288e+233, 1.30741328e+079],
       [1.03321485e-047, 5.01402526e+180],
       [3.09291288e+262, 3.95614168e+252],
       [1.65023927e+137, 2.67276450e+185],
       [2.02446113e+267, 4.85489745e-028]])

In [40]:
#linspace
np.linspace(2,6,7)

array([2.        , 2.66666667, 3.33333333, 4.        , 4.66666667,
       5.33333333, 6.        ])

In [41]:
# Axis = 0 ----> 
# Axis= 1

In [42]:
arr1= np.array([[[1,2,3],[4,5,6],[7,8,9]]])
# arr2 = np.array([[1,2,3],[4,5,6]])

In [43]:
print(arr1)   

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [44]:
print(arr2)

NameError: name 'arr2' is not defined

In [45]:
o/p--->12,15,18
o/p--->6,15,24

SyntaxError: invalid syntax (<ipython-input-45-c3bce53e84be>, line 1)

In [46]:
arr1

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [47]:
arr1.sum()

45

In [48]:
arr1.sum(axis=1)

array([[12, 15, 18]])

In [49]:
arr1.sum(axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [53]:
a = np.array([[10,20,30],[23,34,45],[34,45,87]])

In [54]:
a

array([[10, 20, 30],
       [23, 34, 45],
       [34, 45, 87]])

In [55]:
a.T

array([[10, 23, 34],
       [20, 34, 45],
       [30, 45, 87]])