In [1]:
import numpy as np

In [7]:
myarr =  np.array([1,2,3,4,'me',"dfjdksfb"])

In [8]:
myarr

array(['1', '2', '3', '4', 'me', 'dfjdksfb'], dtype='<U11')

In [9]:
myarr=np.array([[1,2,3,4]])

In [10]:
myarr

array([[1, 2, 3, 4]])

In [11]:
type(myarr)

numpy.ndarray

In [12]:
myarr.shape

(1, 4)

In [13]:
myarr.dtype

dtype('int32')

In [17]:
myarr[0,1]=12

In [18]:
myarr

array([[12, 12, 12, 12]])

In [20]:
myarr[0,2]=21

In [21]:
myarr

array([[12, 12, 21, 12]])

In [22]:
myarr[0]=1

In [23]:
myarr

array([[1, 1, 1, 1]])

In [26]:
np.ones(4)

array([1., 1., 1., 1.])

In [1]:
def common(list1,list2):
    result = False
    for x in list1:
        for y in list2:
            if x==y:
                result =True
                return result
            

In [4]:
print(common([1,2,3,4],[2,9,8,7]))
# common([2,1,9,8])

True


In [14]:
def merge(dict1,dict2):
    res = {**dict1,  **dict2}
    res = dict2.update(dict1)
    return res
dict1={'x':10,'a':1}
dict2 ={'y':20,'c':2}
print(merge(dict1,dict2))
print(dict2)

None
{'y': 20, 'c': 2, 'x': 10, 'a': 1}


In [16]:
#1D
import numpy as np
myarr = np.array([1,2,3])

In [17]:
myarr

array([1, 2, 3])

In [18]:
type(myarr)

numpy.ndarray

In [19]:
myarr = np.array(([1,2,3]))

In [21]:
len(myarr)

3

In [22]:
type(myarr)

numpy.ndarray

In [24]:
print(myarr.ndim)

1


In [28]:
myarr=np.array([[1,2,3],[4,5,6]])

In [29]:
myarr

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
myarr.ndim

2

In [31]:
myarr=np.array([[[1]]])

In [32]:
myarr.ndim

3

In [33]:
myarr=np.array(1)

In [34]:
myarr.ndim

0

In [37]:
myarr = np.array([2,3,6,7])

In [38]:
myarr

array([2, 3, 6, 7])

In [40]:
myarr[2]=200

In [41]:
myarr

array([  2,   3, 200,   7])

In [48]:
np.zeros(((3,2,30)))

array([[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]])

In [49]:
np.ones(1)

array([1.])

In [51]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
np.arange(10,100,3)

array([10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49, 52, 55, 58,
       61, 64, 67, 70, 73, 76, 79, 82, 85, 88, 91, 94, 97])

In [62]:
np.empty((10,2))

array([[1.32180618e-311, 6.27463370e-322],
       [0.00000000e+000, 0.00000000e+000],
       [6.23058367e-307, 5.30276956e+180],
       [1.02941932e-071, 6.98206700e-076],
       [4.86764291e-086, 3.35560116e-143],
       [6.01433264e+175, 6.93885958e+218],
       [5.56218858e+180, 3.94356143e+180],
       [1.36989687e-071, 1.14284075e-071],
       [2.12438857e+160, 1.42608982e-071],
       [7.81586836e-144, 1.50008929e+248]])

In [67]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [68]:
np.arange(99)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

TypeError: _reshape_dispatcher() missing 1 required positional argument: 'newshape'