In [1]:
#Dataframe
# Series
#import data 
#common questions with imported data

In [2]:
import numpy as np

In [3]:
arr = np.array([[1,2,3],[3,4,5],[7,8,9]])

In [4]:
arr

array([[1, 2, 3],
       [3, 4, 5],
       [7, 8, 9]])

In [5]:
arr.T

array([[1, 3, 7],
       [2, 4, 8],
       [3, 5, 9]])

In [6]:
arr.min()

1

In [7]:
arr.max()

9

In [8]:
arr.argmax()

8

In [9]:
arr.argmin()

0

In [10]:
arr = np.array([[3,44,5],[23,67,9],[0,87,9]])

In [11]:
arr

array([[ 3, 44,  5],
       [23, 67,  9],
       [ 0, 87,  9]])

In [12]:
arr.sort()

In [13]:
arr

array([[ 3,  5, 44],
       [ 9, 23, 67],
       [ 0,  9, 87]])

In [14]:
arr.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [15]:
arr = np.array([[3,44,5],[23,67,9],[0,87,9]])

In [16]:
arr

array([[ 3, 44,  5],
       [23, 67,  9],
       [ 0, 87,  9]])

In [17]:
arr.argsort()

array([[0, 2, 1],
       [2, 0, 1],
       [0, 2, 1]], dtype=int64)

# Pandas

In [18]:
arr = np.array([[1, 2, 3],[4, 5, 6], [7, 8, 9]])
# [ 6 15 24]
# [12 15 18]

In [19]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
arr.sum(axis=0)

array([12, 15, 18])

In [21]:
arr.sum(axis=1)

array([ 6, 15, 24])

In [22]:
#Pandas
import pandas as pd

In [23]:
dict ={
    'name':['Ankit','Aman','Raju'],
    'city':['UP','Punjab','Haryana'],
    'marks':[22,45,89]
    
}

In [24]:
dict

{'name': ['Ankit', 'Aman', 'Raju'],
 'city': ['UP', 'Punjab', 'Haryana'],
 'marks': [22, 45, 89]}

In [25]:
#make a data frame
df = pd.DataFrame(dict)

In [26]:
df

name     city  marks
0  Ankit       UP     22
1   Aman   Punjab     45
2   Raju  Haryana     89

In [28]:
 df.to_csv('mydata.csv')

In [29]:
df

name     city  marks
0  Ankit       UP     22
1   Aman   Punjab     45
2   Raju  Haryana     89

In [31]:
df.to_csv('newdata.csv',index=False)

In [34]:
#load dataset
df = pd.read_csv('D:\ML_challenge\Covid-19_Dataset\COVID 19 ML Model Data\covid_19_clean_complete.csv')

In [35]:
df

Province/State         Country/Region      Lat      Long     Date  \
0                NaN               Thailand  15.0000  101.0000  1/22/20   
1                NaN                  Japan  36.0000  138.0000  1/22/20   
2                NaN              Singapore   1.2833  103.8333  1/22/20   
3                NaN                  Nepal  28.1667   84.2500  1/22/20   
4                NaN               Malaysia   2.5000  112.5000  1/22/20   
...              ...                    ...      ...       ...      ...   
19215            NaN                 Jersey  49.1900   -2.1100  3/23/20   
19216            NaN            Puerto Rico  18.2000  -66.5000  3/23/20   
19217            NaN  Republic of the Congo  -1.4400   15.5560  3/23/20   
19218            NaN            The Bahamas  24.2500  -76.0000  3/23/20   
19219            NaN             The Gambia  13.4667  -16.6000  3/23/20   

       Confirmed  Deaths  Recovered  
0            2.0     0.0        0.0  
1            2.0     0.0        0.0  
2            0.0     0.0        0.0  
3            0.0     0.0        0.0  
4            0.0     0.0        0.0  
...          ...     ...        ...  
19215        0.0     0.0        0.0  
19216        0.0     1.0        0.0  
19217        0.0     0.0        0.0  
19218        0.0     0.0        0.0  
19219        0.0     0.0        0.0  

[19220 rows x 8 columns]

In [36]:
df.head()

Province/State Country/Region      Lat      Long     Date  Confirmed  \
0            NaN       Thailand  15.0000  101.0000  1/22/20        2.0   
1            NaN          Japan  36.0000  138.0000  1/22/20        2.0   
2            NaN      Singapore   1.2833  103.8333  1/22/20        0.0   
3            NaN          Nepal  28.1667   84.2500  1/22/20        0.0   
4            NaN       Malaysia   2.5000  112.5000  1/22/20        0.0   

   Deaths  Recovered  
0     0.0        0.0  
1     0.0        0.0  
2     0.0        0.0  
3     0.0        0.0  
4     0.0        0.0

In [37]:
df.tail()

Province/State         Country/Region      Lat    Long     Date  \
19215            NaN                 Jersey  49.1900  -2.110  3/23/20   
19216            NaN            Puerto Rico  18.2000 -66.500  3/23/20   
19217            NaN  Republic of the Congo  -1.4400  15.556  3/23/20   
19218            NaN            The Bahamas  24.2500 -76.000  3/23/20   
19219            NaN             The Gambia  13.4667 -16.600  3/23/20   

       Confirmed  Deaths  Recovered  
19215        0.0     0.0        0.0  
19216        0.0     1.0        0.0  
19217        0.0     0.0        0.0  
19218        0.0     0.0        0.0  
19219        0.0     0.0        0.0

In [39]:
df.head(10)

Province/State Country/Region      Lat      Long     Date  Confirmed  \
0               NaN       Thailand  15.0000  101.0000  1/22/20        2.0   
1               NaN          Japan  36.0000  138.0000  1/22/20        2.0   
2               NaN      Singapore   1.2833  103.8333  1/22/20        0.0   
3               NaN          Nepal  28.1667   84.2500  1/22/20        0.0   
4               NaN       Malaysia   2.5000  112.5000  1/22/20        0.0   
5  British Columbia         Canada  49.2827 -123.1207  1/22/20        0.0   
6   New South Wales      Australia -33.8688  151.2093  1/22/20        0.0   
7          Victoria      Australia -37.8136  144.9631  1/22/20        0.0   
8        Queensland      Australia -28.0167  153.4000  1/22/20        0.0   
9               NaN       Cambodia  11.5500  104.9167  1/22/20        0.0   

   Deaths  Recovered  
0     0.0        0.0  
1     0.0        0.0  
2     0.0        0.0  
3     0.0        0.0  
4     0.0        0.0  
5     0.0        0.0  
6     0.0        0.0  
7     0.0        0.0  
8     0.0        0.0  
9     0.0        0.0

In [40]:
df.tail(10)

Province/State         Country/Region      Lat      Long  \
19210  United States Virgin Islands                     US  18.3358  -64.8963   
19211                            US                     US  37.0902  -95.7129   
19212                           NaN              Greenland  72.0000  -40.0000   
19213                           NaN                   Guam  13.4443  144.7937   
19214                           NaN               Guernsey  49.4500   -2.5800   
19215                           NaN                 Jersey  49.1900   -2.1100   
19216                           NaN            Puerto Rico  18.2000  -66.5000   
19217                           NaN  Republic of the Congo  -1.4400   15.5560   
19218                           NaN            The Bahamas  24.2500  -76.0000   
19219                           NaN             The Gambia  13.4667  -16.6000   

          Date  Confirmed  Deaths  Recovered  
19210  3/23/20        6.0     0.0        0.0  
19211  3/23/20        1.0     0.0      178.0  
19212  3/23/20        0.0     0.0        0.0  
19213  3/23/20        0.0     1.0        0.0  
19214  3/23/20        0.0     0.0        0.0  
19215  3/23/20        0.0     0.0        0.0  
19216  3/23/20        0.0     1.0        0.0  
19217  3/23/20        0.0     0.0        0.0  
19218  3/23/20        0.0     0.0        0.0  
19219  3/23/20        0.0     0.0        0.0

In [42]:
df.sample(10)

Province/State            Country/Region      Lat      Long     Date  \
15783            NaN          Papua New Guinea  -6.3150  143.9555  3/12/20   
13968            NaN                     Spain  40.0000   -4.0000   3/7/20   
3654             NaN  Central African Republic   6.6111   20.9394   2/2/20   
16480            NaN                   Ireland  53.1424   -7.6921  3/15/20   
2007     Mississippi                        US  32.7416  -89.6787  1/28/20   
16319            NaN                  Honduras  15.2000  -86.2419  3/14/20   
15018      Louisiana                        US  31.1695  -91.8678  3/10/20   
1000             NaN                   Hungary  47.1625   19.5033  1/25/20   
4072             NaN                San Marino  43.9424   12.4578   2/4/20   
17212          Anhui                     China  31.8257  117.2264  3/17/20   

       Confirmed  Deaths  Recovered  
15783        0.0     0.0        0.0  
13968      500.0    10.0       30.0  
3654         0.0     0.0        0.0  
16480      129.0     2.0        0.0  
2007         0.0     0.0        0.0  
16319        2.0     0.0        0.0  
15018        1.0     0.0        0.0  
1000         0.0     0.0        0.0  
4072         0.0     0.0        0.0  
17212      990.0     6.0      984.0

In [43]:
df.columns

Index(['Province/State', 'Country/Region', 'Lat', 'Long', 'Date', 'Confirmed',
       'Deaths', 'Recovered'],
      dtype='object')

In [45]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19220 entries, 0 to 19219
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Province/State  8432 non-null   object 
 1   Country/Region  19220 non-null  object 
 2   Lat             19220 non-null  float64
 3   Long            19220 non-null  float64
 4   Date            19220 non-null  object 
 5   Confirmed       19219 non-null  float64
 6   Deaths          19219 non-null  float64
 7   Recovered       19219 non-null  float64
dtypes: float64(5), object(3)
memory usage: 1.2+ MB


In [47]:
df.isnull().sum()

Province/State    10788
Country/Region        0
Lat                   0
Long                  0
Date                  0
Confirmed             1
Deaths                1
Recovered             1
dtype: int64

In [48]:
df.describe()

Lat          Long     Confirmed        Deaths     Recovered
count  19220.000000  19220.000000  19219.000000  19219.000000  19219.000000
mean      25.088643      5.289362    287.734586     10.237994    103.066341
std       23.448518     80.081866   3297.651489    155.703574   1795.041235
min      -41.454500   -157.498300      0.000000      0.000000      0.000000
25%       12.518600    -70.162700      0.000000      0.000000      0.000000
50%       31.221000      9.775000      0.000000      0.000000      0.000000
75%       42.165700     57.500000      8.000000      0.000000      0.000000
max       72.000000    178.065000  67800.000000   5476.000000  59879.000000