In [8]:
#5 
def compare(list1,list2): 
    for x in list1:
        for y in list2:
            if x==y:
                return True
#             else:
    return False       
list1=[1,2,3,4]
list2=[8,9,0,2]
compare(list1,list2)            



True

In [9]:
#multiply
a=[2,3,4,5]
pro = 1
for i in a:
    pro= pro*i
print(pro)    
    

120


In [12]:
dict1 ={'x':10,'y':90}
dict2 = {'a':89,'u':78}
print(dict2.update(dict1))
print(dict2)

None
{'a': 89, 'u': 78, 'x': 10, 'y': 90}


In [13]:
#Libraries
#Numpy,Pandas,Matplotlib,Seaborn
import numpy as np

In [21]:
# 0,1,2,3
# 1-D
myarr = np.array([1,2,34])

In [22]:
print(myarr)

[ 1  2 34]


In [16]:
type(myarr)

numpy.ndarray

In [28]:
# 1-D
arr =np.array([1,])

In [29]:
arr

array([1])

In [30]:
type(arr)

numpy.ndarray

In [31]:
myarr.ndim

1

In [32]:
arr.ndim

1

In [59]:
# 2-D array
myarr = np.array([[1,2,3],[2,2,4,6]])

<ipython-input-59-47b9dc31f217>:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  myarr = np.array([[1,2,3],[2,2,4,6]])


In [49]:
myarr

array([list([1, 2, 3]), list([2, 2, 445, 6])], dtype=object)

In [50]:
type(myarr)

numpy.ndarray

In [52]:
myarr.ndim

1

In [55]:
myarr = np.array([[1,2,3],[2,2,6]])

In [56]:
myarr

array([[1, 2, 3],
       [2, 2, 6]])

In [57]:
type(myarr)

numpy.ndarray

In [58]:
myarr.ndim

2

In [68]:
# 1d,2d,
myarr = np.array([[1,2,3],[2,6,2]])

In [65]:
myarr

array([[1, 2, 3],
       [2, 6, 2]])

In [66]:
myarr.ndim

2

In [73]:
#3d
x = np.array([[1,23,3],[3,4,5],[4,5,6]])

In [74]:
x

array([[ 1, 23,  3],
       [ 3,  4,  5],
       [ 4,  5,  6]])

In [71]:
x.ndim

3

In [85]:
x = np.array([[[1,23,3]]])

In [86]:
print(x)

[[[ 1 23  3]]]


In [87]:
x.ndim

3

In [82]:
x = np.array([[[1,23,3],[3,4,5],[4,5,6]]])

In [83]:
x

array([[[[ 1, 23,  3],
         [ 3,  4,  5],
         [ 4,  5,  6]]]])

In [84]:
x.ndim

4

In [88]:
my = np.array([1,2,3],[2,3,4],[3,4,5])

TypeError: array() takes from 1 to 2 positional arguments but 3 were given

In [96]:
# numpy 
#zeros
#ones
np.zeros(200)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [99]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [102]:
np.zeros((2,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [104]:
#ones
np.ones(2)

array([1., 1.])

In [105]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [109]:
np.ones(50)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [115]:
np.ones((2,1,20))

array([[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1.]]])

In [116]:
np.identity(2)

array([[1., 0.],
       [0., 1.]])

In [121]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])